# Generated by Django 3.2.10 on 2023-11-27 12:21

from django.db import migrations, models
import request_pool.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLMRequest',
            fields=[
                ('code', models.CharField(default=request_pool.models.generate_code, max_length=10, primary_key=True, serialize=False)),
                ('input_data', models.JSONField(default=request_pool.models.inputDefault, null=True)),
                ('response_data', models.JSONField(default=request_pool.models.outputDefault, null=True)),
                ('succeed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
